/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'accountAws', { get: function () { return require('./account-aws'); } });
Object.defineProperty(exports, 'credentialsAws', { get: function () { return require('./credentials-aws'); } });
Object.defineProperty(exports, 'dataIntegration', { get: function () { return require('./data-integration'); } });
Object.defineProperty(exports, 'elastigroupAws', { get: function () { return require('./elastigroup-aws'); } });
Object.defineProperty(exports, 'elastigroupAwsBeanstalk', { get: function () { return require('./elastigroup-aws-beanstalk'); } });
Object.defineProperty(exports, 'elastigroupAwsSuspension', { get: function () { return require('./elastigroup-aws-suspension'); } });
Object.defineProperty(exports, 'elastigroupAzureV3', { get: function () { return require('./elastigroup-azure-v3'); } });
Object.defineProperty(exports, 'elastigroupGcp', { get: function () { return require('./elastigroup-gcp'); } });
Object.defineProperty(exports, 'elastigroupGke', { get: function () { return require('./elastigroup-gke'); } });
Object.defineProperty(exports, 'healthCheck', { get: function () { return require('./health-check'); } });
Object.defineProperty(exports, 'managedInstanceAws', { get: function () { return require('./managed-instance-aws'); } });
Object.defineProperty(exports, 'mrscalerAws', { get: function () { return require('./mrscaler-aws'); } });
Object.defineProperty(exports, 'oceanAksNp', { get: function () { return require('./ocean-aks-np'); } });
Object.defineProperty(exports, 'oceanAksNpVirtualNodeGroup', { get: function () { return require('./ocean-aks-np-virtual-node-group'); } });
Object.defineProperty(exports, 'oceanAws', { get: function () { return require('./ocean-aws'); } });
Object.defineProperty(exports, 'oceanAwsExtendedResourceDefinition', { get: function () { return require('./ocean-aws-extended-resource-definition'); } });
Object.defineProperty(exports, 'oceanAwsLaunchSpec', { get: function () { return require('./ocean-aws-launch-spec'); } });
Object.defineProperty(exports, 'oceanEcs', { get: function () { return require('./ocean-ecs'); } });
Object.defineProperty(exports, 'oceanEcsLaunchSpec', { get: function () { return require('./ocean-ecs-launch-spec'); } });
Object.defineProperty(exports, 'oceanGkeImport', { get: function () { return require('./ocean-gke-import'); } });
Object.defineProperty(exports, 'oceanGkeLaunchSpec', { get: function () { return require('./ocean-gke-launch-spec'); } });
Object.defineProperty(exports, 'oceanGkeLaunchSpecImport', { get: function () { return require('./ocean-gke-launch-spec-import'); } });
Object.defineProperty(exports, 'oceanSpark', { get: function () { return require('./ocean-spark'); } });
Object.defineProperty(exports, 'oceanSparkVirtualNodeGroup', { get: function () { return require('./ocean-spark-virtual-node-group'); } });
Object.defineProperty(exports, 'oceancdRolloutSpec', { get: function () { return require('./oceancd-rollout-spec'); } });
Object.defineProperty(exports, 'oceancdStrategy', { get: function () { return require('./oceancd-strategy'); } });
Object.defineProperty(exports, 'oceancdVerificationProvider', { get: function () { return require('./oceancd-verification-provider'); } });
Object.defineProperty(exports, 'oceancdVerificationTemplate', { get: function () { return require('./oceancd-verification-template'); } });
Object.defineProperty(exports, 'organizationPolicy', { get: function () { return require('./organization-policy'); } });
Object.defineProperty(exports, 'organizationProgrammaticUser', { get: function () { return require('./organization-programmatic-user'); } });
Object.defineProperty(exports, 'organizationUser', { get: function () { return require('./organization-user'); } });
Object.defineProperty(exports, 'organizationUserGroup', { get: function () { return require('./organization-user-group'); } });
Object.defineProperty(exports, 'statefulNodeAzure', { get: function () { return require('./stateful-node-azure'); } });
Object.defineProperty(exports, 'subscription', { get: function () { return require('./subscription'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

